workflows:
  unity-android-build:
    name: Unity Android Build
    instance_type: linux_x2
    max_build_duration: 120
    environment:
      vars:
        UNITY_VERSION: 2022.3.0f1
        PACKAGE_NAME: "com.kljdflakj.AirBalloon"
        KEYSTORE_PATH: "android.keystore"
        KEY_ALIAS: "airballoon_key"
        KEYSTORE_PASSWORD: "secure_password"  # Используйте Codemagic Secrets
        KEY_PASSWORD: "secure_password"
      android_signing:
        - name: "play_store"
          type: keystore
          keystore: $KEYSTORE_PATH  # Обязательное поле
          store_password: $KEYSTORE_PASSWORD
          key_alias: $KEY_ALIAS
          key_password: $KEY_PASSWORD
          group: default
    scripts:
      - name: Install Unity
        script: |
          unityhub install --version $UNITY_VERSION --child-modules android
      - name: Generate Keystore
        script: |
          if [ ! -f "$KEYSTORE_PATH" ]; then
            keytool -genkey -v -keystore $KEYSTORE_PATH -alias $KEY_ALIAS \
              -storepass $KEYSTORE_PASSWORD -keypass $KEY_PASSWORD \
              -keyalg RSA -keysize 2048 -validity 10000 \
              -dname "CN=AirBalloon, OU=Dev, O=Kljdflakj, L=City, S=State, C=US"
          fi
      - name: Configure and Build
        script: |
          unity-editor \
            -batchmode \
            -nographics \
            -silent-crashes \
            -logFile /dev/stdout \
            -projectPath . \
            -executeMethod BuildScript.PerformBuild \
            -quit
    artifacts:
      - build/*.apk
      - $KEYSTORE_PATH