workflows:
  unity-android-workflow:
    name: Unity Android Workflow
    max_build_duration: 120
    triggering:
      events:
        - push
        - tag
        - pull_request
    scripts:
      - name: variable check
        script: echo $UNITY_HOME
      
      - name: Build the project
        script: | 
          Unity -batchmode \
            -quit \
            -logFile \
            -projectPath . \
            -executeMethod BuildScript.BuildAndroid \
            -nographics

    artifacts:
      - android/*.aab
      - android/*.apk