workflows:
  unity-build:
    name: Unity Build Workflow
    environment:
      groups:
        - unity_credentials # Группа с переменными окружения для Unity (например, UNITY_EMAIL, UNITY_PASSWORD, UNITY_SERIAL)
      vars:
        UNITY_VERSION: 2020.3.33f1 # Версия Unity, которую вы хотите использовать
        BUILD_TARGET: Android # Цель сборки (Android, iOS, WebGL и т.д.)
    scripts:
      - name: Install Unity
        script: |
          echo "Installing Unity Editor $UNITY_VERSION"

          # Установка зависимостей
          sudo apt-get update
          sudo apt-get install -y libgconf-2-4 libxi6 libxtst6 libxrandr2 libgtk2.0-0 libxss1 libasound2

          # Скачивание и установка Unity Editor
          UNITY_DOWNLOAD_URL="https://download.unity3d.com/download_unity/$(curl -s https://unity.com/releases/editor/whats-new/$UNITY_VERSION | grep -oP '(?<=<p>Changeset: )[^<]+')/Linux/Unity.tar.gz"
          wget -q "$UNITY_DOWNLOAD_URL" -O Unity.tar.gz
          sudo mkdir -p /opt/Unity
          sudo tar -xzf Unity.tar.gz -C /opt/Unity
          rm Unity.tar.gz

          # Проверка установки
          /opt/Unity/Editor/Unity -version
      - name: Set up Android SDK
        script: |
          echo "Setting up Android SDK"
          sudo apt-get install -y --no-install-recommends openjdk-8-jdk
          export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"
      - name: Build Unity Project
        script: |
          echo "Building Unity project for $BUILD_TARGET"
          /opt/Unity/Editor/Unity \
            -batchmode \
            -nographics \
            -silent-crashes \
            -logFile /tmp/unity_build.log \
            -projectPath "$CM_BUILD_DIR" \
            -buildTarget $BUILD_TARGET \
            -executeMethod BuildScript.PerformBuild \
            -quit
          cat /tmp/unity_build.log
    artifacts:
      - build/**/*.apk # Путь к собранному APK-файлу (для Android)
    publishing:
      email:
        recipients:
          - ilya.smolenskiy.00@gmail.com